---
title: "genome variation and completeness"
output:
  html_notebook:
    code_folding: hide
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
current_directory <- dirname(rstudioapi::getActiveDocumentContext()$path)
knitr::opts_knit$set(root.dir=normalizePath(paste0(current_directory)))
```

```{r load_libraries, include=FALSE}
## load libraries
library(viridis) 
library(ggpubr) 
library(ggrepel)
library(plotmo)
library(tidyverse) 
```

```{r fig.width=8.75, fig.height=5}
## read in data
bagged_pheno_allhomo <- read.csv("dataFiles/09.00_bagged_phenoresults_allhomo.csv")

## lifespan correlation plot (for main figure)
busco <- (ggscatter(data = bagged_pheno_allhomo,
          x = "b_complete", 
          y = "bagged_detrans_relative_error", 
          add = "reg.line", 
          xlab = "Genome completeness\n(%)", 
          ylab = "Prediction error (%)",
          shape=21,
          alpha = 0.7, 
          size=1.75,
          ggtheme = theme_classic(),
          fill = "bagged_detrans_absolute_error",
          legend = "right", 
          legend.title = "Prediction error (years)") +
 stat_cor(aes(label = paste(..r.label.., ..rr.label.., 
                            ..p.label.., sep = "~`,`~")), 
           label.x.npc = 0.05, 
           label.y.npc = 0.05, 
           size=3.3)+
   scale_fill_viridis_c(option = "D", trans="log10", 
                        direction=1)+
  scale_shape_manual(values=c(21, 23), guide = "none"))+
  scale_y_log10()

# busco
```

```{r fig.width=8.75, fig.height=5}
## read in data
bagged_pheno_allhomo <- read.csv("dataFiles/09.00_bagged_phenoresults_allhomo.csv")

## lifespan correlation plot (for main figure)
busco2 <- (ggscatter(data = bagged_pheno_allhomo,
                     x = "b_complete", 
                     y = "bagged_detrans_absolute_error", 
                     add = "reg.line", 
                     xlab = "Genome completeness\n(%)", 
                     ylab = "Prediction error (years)",
                     shape=21,
                     alpha = 0.7, 
                     size=1,
                     ggtheme = theme_classic(),
                     fill = "grey70",
                     color="grey70",
                     legend = "right", 
                     legend.title = "Prediction error (years)") +
             stat_cor(aes(label = paste(..r.label.., ..rr.label.., 
                                        ..p.label.., sep = "~`,`~")), 
                      label.x.npc = 0.05, 
                      label.y.npc = 0.05, 
                      fill="grey70",
                      size=2)+
             scale_shape_manual(values=c(21, 23), guide = "none"))+
  scale_y_log10()

busco2
```

```{r}
busco3 <- ggplot(data = bagged_pheno_allhomo,
                 aes(x = b_complete, 
                     y = bagged_detrans_absolute_error)) +
  theme_classic()+
  geom_point(fill="grey70", 
             stroke=0.25,
             alpha=0.5,
             shape=21, 
             size=0.9)+
    labs(y="Prediction error (years)", 
         x="Genome completeness\n(%)")+
  scale_y_log10(labels = ~ format(.x, scientific = FALSE))+
  scale_x_log10(labels = ~ format(.x, scientific = FALSE))+
  geom_smooth(color="grey70",
              method=lm,
              se=FALSE)+
  stat_cor(aes(label = paste(after_stat(r.label),
                             after_stat(rr.label),
                             after_stat(p.label),
                             sep = "~`,`~")),
           color="grey70",
           label.x.npc = 0.001,
           label.y.npc = 0.05,
           size=2)
busco3
```

```{r}
## create viridis colour scale
custom_viridis <- viridis_pal(option = "D", direction=-1)(4)[2:4]

## change the first colour
custom_viridis <- c("grey70", custom_viridis)

bagged_pheno_all <- rbind(rbind(rbind(
  read.csv("dataFiles/09.00_bagged_phenoresults_allhomo.csv") %>% mutate(model = "All-vertebrate"),
  read.csv("dataFiles/09.00_bagged_phenoresults_fishdanio.csv") %>% mutate(model = "Fish")),
  read.csv("dataFiles/09.00_bagged_phenoresults_reptilesgallus.csv") %>% mutate(model = "Reptiles")),
  read.csv("dataFiles/09.00_bagged_phenoresults_mammalshomo.csv") %>% mutate(model = "Mammals"))

busco4 <- ggplot(data = bagged_pheno_all,
                 aes(x = b_complete, 
                     y = bagged_detrans_absolute_error)) +
  theme_classic()+
  geom_point(aes(fill=model), 
             # fill="grey70", 
             stroke=0.25,
             alpha=0.5,
             shape=21, 
             size=0.9)+
    labs(y="Prediction error (years)", 
         x="Genome completeness\n(%)")+
  scale_y_log10(labels = ~ format(.x, scientific = FALSE))+
  scale_x_log10(labels = ~ format(.x, scientific = FALSE))+
  scale_color_manual(values=custom_viridis, guide="none", drop=FALSE)+
  scale_fill_manual(values=custom_viridis, name="", drop=FALSE)+
  geom_smooth(aes(color=model),
              # color="grey70",
              method=lm,
              se=FALSE)+
  stat_cor(aes(label = paste(after_stat(r.label),
                             after_stat(rr.label),
                             after_stat(p.label),
                             sep = "~`,`~"),
               color=model),
           # color="grey70",
           label.x.npc = 0.001,
           label.y.npc = 0.25,
           size=2)+
  theme(legend.position="none")

busco4
```

```{r}
summary(with(bagged_pheno_allhomo, glm(log(bagged_detrans_relative_error) ~ b_complete)))
```

```{r}
## PLOT DATA ----

## bag the model estimates
bagged_pheno_fc <- read.csv("dataFiles/14.00_bagged_phenoresults_allhomofc.csv") 

## list species
unique(bagged_pheno_fc$organism_name)

## add some plotting info (not all of this is needed)
bagged_pheno_fc_plot <- bagged_pheno_fc %>%
  ## scaled genome size
  group_by(organism_name) %>%
  mutate(median_bagged_detrans_predicted_age_mat = median(bagged_detrans_predicted_age_mat), 
         absolute_deviation = 
           abs(median_bagged_detrans_predicted_age_mat-bagged_detrans_predicted_age_mat)) %>%
  mutate(relative_n50 = assembly_stats_contig_n50 / sum(assembly_stats_contig_n50, na.rm=TRUE)) %>%
  ## add if modelled genome
  mutate(modelled_genome = ifelse(assembly_id %in% bagged_pheno_allhomo$assembly_id, 
                                  "Yes", 
                                  "No")) %>%
  ## add common names
  mutate(common_name = gsub("", "", organism_name) %>%
           gsub("Rattus norvegicus", "Brown rat", .) %>%
           gsub("Loxodonta africana", "African elephant", .) %>%
           gsub("Macaca mulatta", "Rhesus macaque", .) %>%
           gsub("Equus caballus", "Horse", .) %>%
           gsub("Callithrix jacchus", "Common marmoset", .) %>%
           gsub("Bubalus bubalis", "Water buffalo", .) %>%
           gsub("Capra hircus", "Goat", .) %>%
           gsub("Cyprinus carpio", "Common carp", .) %>%
           gsub("Scleropages formosus", "Asian arowana", .) %>%
           gsub("Oncorhynchus mykiss", "Rainbow trout", .) %>%
           gsub("Delphinapterus leucas", "Beluga whale", .) %>%
           gsub("Scophthalmus maximus", "Turbot", .) %>%
           gsub("Pygoscelis papua", "Gentoo penguin", .) %>%
           gsub("Elephas maximus", "Asian elephant", .)) %>%
  ## add species label
  mutate(species_label = paste0(common_name, "\n(*", organism_name, "*)")) %>%
  ## edit sex
  mutate(sex = ifelse(organism_infraspecific_names_sex == "female", 
                      "Female", 
                      ifelse(organism_infraspecific_names_sex == "male", 
                             "Male",
                             "Unknown"))) %>%
  mutate(sex = replace_na(sex, "Unknown")) %>%
  ## order by median age
  # arrange(median_bagged_detrans_predicted_age_mat) %>%
  ## order by species name
  arrange(desc(species_label))
```

```{r}
## create fc table for supplementary
fc_table <- bagged_pheno_fc_plot %>%
  mutate(`Predicted age at sexual maturity (years)` = round(bagged_detrans_predicted_age_mat, digits=2)) %>%
  group_by(organism_name) %>%
  mutate(`Mean predicted age at sexual maturity (±SD)` = 
           paste0(round(mean(bagged_detrans_predicted_age_mat), digits=2), 
                  " ± ", 
                  round(sd(bagged_detrans_predicted_age_mat), digits=2))) %>%
  select(organism_name,
         assembly_accession,
         biosample,
         b_complete,
         modelled_genome,
         `Predicted age at sexual maturity (years)`, 
         `Mean predicted age at sexual maturity (±SD)`) %>%
  rename(Species = organism_name,
         `Assembly accession` = assembly_accession,
         Biosample = biosample, 
         `BUSCO completeness score (%)` = b_complete,
         `Modelled genome (Yes/No)` = modelled_genome) %>%
  arrange(Species)

## save it
write.csv(fc_table, "figuresTables/Table S[fc_table].csv", row.names=FALSE)
```

```{r fig.width=8.75, fig.height=5}
## BUSCO ----

fc<-ggerrorplot(bagged_pheno_fc_plot, 
                x = "species_label", 
                y = "bagged_detrans_predicted_age_mat", 
                desc_stat = "median_iqr",
                color = "black")+
  labs(x="Species", y="Predicted age at sexual maturity (years)")+
  coord_flip()+
  scale_fill_viridis_c(option="D", direction = 1,
                       name="Genome completeness (%)")+
  theme_classic()+
  theme(axis.text.y = ggtext::element_markdown(), ## for italics
        legend.position="right")+
  # ylim(c(1, 10))+
  scale_y_log10(limits = c(1, 10))+
  geom_jitter(position = sdamr::position_jitternudge(jitter.width = 0.01,
                                                     nudge.x = -0.3),
              alpha=0.75,
              # pch=21,
              aes(fill=b_complete,
                  shape = sex,
                  size=relative_n50))+
  scale_shape_manual(values=c(21, 22, 23),
                     name="Sex")+
  scale_size("Genome contiguity (relative n50)", 
             range = c(1, 4))

fc
```

```{r}
summary(with(bagged_pheno_fc_plot, glm(absolute_deviation ~ relative_n50)))
summary(with(bagged_pheno_fc_plot, glm(absolute_deviation ~ b_complete)))
summary(with(bagged_pheno_fc_plot, glm(absolute_deviation ~ relative_n50 + b_complete)))
```



```{r fig.width=8.75, fig.height=5}
gen_comp <- ggarrange(fc+theme(legend.position="bottom", 
                   legend.box = "vertical", 
                   legend.margin=margin(c(0,0,0,0))), 
          busco+theme(legend.position="bottom"),
          nrow=1, 
          widths=c(1, 0.7),
          labels=c("A", "B"))

gen_comp

ggsave(paste0("figuresTables/Figure [gen_comp].png"),
       gen_comp,
       width = 8.75*1.3,
       height = 11.25/3*1.3,
       units = "in")
```

```{r}
## lifespan correlation plot (for main figure)
contig <- (ggscatter(data = bagged_pheno_fc_plot,
          x = "relative_n50", 
          y = "absolute_deviation", 
          add = "reg.line", 
          xlab = "Genome contiguity (relative n50)", 
          ylab = "Absolute deviation",
          shape=21,
          alpha = 0.7, 
          size=1.75,
          ggtheme = theme_bw()) +
 stat_cor(aes(label = paste(..r.label.., ..rr.label.., 
                            ..p.label.., sep = "~`,`~")), 
          method="kendall",
           label.x.npc = 0.05, 
           label.y.npc = 0.95, 
           size=3.3))+
  scale_y_log10()

busco_dev <- (ggscatter(data = bagged_pheno_fc_plot,
          x = "b_complete", 
          y = "absolute_deviation", 
          add = "reg.line", 
          xlab = "Genome completeness (%)", 
          ylab = "Absolute deviation",
          shape=21,
          alpha = 0.7, 
          size=1.75,
          ggtheme = theme_bw()) +
 stat_cor(aes(label = paste(..r.label.., ..rr.label.., 
                            ..p.label.., sep = "~`,`~")), 
          method="kendall",
           label.x.npc = 0.05, 
           label.y.npc = 0.95, 
           size=3.3))+
  scale_y_log10()


ggarrange(contig, busco_dev)
```
```{r}
## add to error figure
error_plot <- readRDS("figuresTables/Figure [error_both].rds")
```

```{r fig.width=8.75, fig.height=10}
err_gen_comp <- ggarrange(error_plot, 
          ggarrange(fc+theme(panel.grid.major.y = element_line(colour="grey", size=0.1),
                             legend.title=element_text(size=10),
                             legend.position="bottom", 
                             legend.box = "vertical", 
                             legend.margin=margin(c(-0.2,0,-0.2,0), unit='cm'))+
                      guides(fill = guide_colourbar(barheight = 0.9))+
                      scale_fill_viridis(option="rocket", name="Genome completeness (%)"), 
                    ggarrange(busco4+theme(legend.position="none", 
                                           axis.title.y=element_text(size=10),
                                          axis.title.x=element_text(size=9)), 
                              NULL, nrow=2, heights=c(1, 0.25)),
                    nrow=1, 
                    widths=c(1, 0.375),
                    labels=c("C", "D")),
          heights = c(1, 0.6),
          nrow=2)

err_gen_comp

ggsave(paste0("figuresTables/Figure [err_gen_comp].png"),
       err_gen_comp,
       width = 8.75,
       height = 10,
       units = "in")

ggsave(paste0("figuresTables/Figure [err_gen_comp].svg"),
       err_gen_comp,
       width = 8.75,
       height = 10,
       units = "in")
```


```{r}
## END SCRIPT 
```

