---
title: "iucn assessment"
author: "Alyssa"
date: "`r Sys.Date()`"
output:
  html_notebook:
    code_folding: hide
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, warning=FALSE, message=FALSE}
current_directory <- dirname(rstudioapi::getActiveDocumentContext()$path)
knitr::opts_knit$set(root.dir=normalizePath(paste0(current_directory)))
```

```{r warning=FALSE, message=FALSE}
## load libraries
library(viridis)
# library(ggrepel)
# library(taxize)
library(ggstance)
library(ggtree)
library(ape)
# library(phytools)
library(ggpubr)
library(multcomp)
library(tidyverse)
```

```{r}
## IMPORT, FORMAT AND EXPORT DATA ----

## define models ----
models <- c("fishdaniounknowns", 
            "mammalshomounknowns", "reptilesgallusunknowns")

# models <- c("allhomo")

## pheno/results ----
bagged_unknowns_all_unmod <- NULL
for (mod in models){
  
  ## import data
  bagged_phenoresults_unknowns <- 
    read.csv(paste0("dataFiles/13.00_bagged_phenoresults_unknowns_", mod, ".csv"))
  
  ## combine
  bagged_unknowns_all_unmod <- bind_rows(bagged_unknowns_all_unmod, bagged_phenoresults_unknowns)
  
  ## name it
  assign(paste0("bagged_phenoresults_", mod), bagged_phenoresults_unknowns)
}

## import common names for main
cmn_nms <- read.csv("../B_exploreData/dataFiles/00.02_genbank_full_vert_genomes_meta.csv") %>%
  select(organism_name, common_name)

## add labels and names
bagged_unknowns_all <- bagged_unknowns_all_unmod %>%
  mutate(model_type = ifelse(model_labs == "All-vertebrate", 
                             model_labs, 
                             "Group-specific")) %>%
  left_join(., cmn_nms) %>%
  mutate(common_name = case_when(
    organism_name == "Dermatemys mawii" ~ "Central American river turtle",
    organism_name == "Thalassophryne amazonica" ~ "Amazon freshwater toadfish",
    organism_name == "Sebastes koreanus" ~ "Korean rockfish",
    organism_name == "Olivaichthys viedmensis" ~ "Argentinian velvet catfish",
    organism_name == "Molossus alvarezi" ~ "Alvarez's mastiff bat",
    organism_name == "Gogo arcuatus" ~ "Madagascan catfish",
    organism_name == "Platytropius siamensis" ~ "Siamese schilbeid catfish",
    organism_name == "Lepidodactylus listeri" ~ "Christmas Island gecko",
    organism_name == "Cryptoblepharus egeriae" ~ "Christmas Island skink",
    organism_name == "Hemibagrus guttatus" ~ "Spotted longbarbel catfish",
    organism_name == "Hydrophis melanocephalus" ~ "Slender-necked sea snake",
    organism_name == "Ctenochaetus hawaiiensis" ~ "Hawaiian surgeonfish",
    organism_name == "Syndactyla subalaris" ~ "Lineated foliage-gleaner",
    organism_name == "Hypsolebias longignatus" ~ "South American killifish",
    organism_name == "Cacajao hosomi" ~ "Neblina uakari",
    organism_name == "Leucopsar rothschildi" ~ "Bali myna",
    organism_name == "Danionella dracula" ~ "Dracula fish",
    organism_name == "Poropuntius huangchuchieni" ~ "Mekong freshwater cyprinid",
    # organism_name == "Scientific name" ~ "Common name",
    TRUE ~ common_name)) %>%
  mutate(common_name = case_when(common_name == "NULL" ~ "Unknown",
                                 TRUE ~ common_name)) %>%
  mutate(name_lab = paste0(common_name, " (*", organism_name, "*)")) %>%
  mutate(name_lab2 = paste0(common_name, "\n(*", organism_name, "*)")) %>%
  ## edit IUCN categories
  mutate(redlist_cat_unmod = redlist_cat) %>%
  mutate(redlist_cat = case_when(
    redlist_cat_unmod == "Extinct in the Wild" ~ "Extinct",
    redlist_cat_unmod == "Lower Risk/near threatened" ~ "Near Threatened",
    # redlist_cat_unmod == "old name" ~ "new name",
    TRUE ~ redlist_cat)) %>%
  ## order by redlist cat
  arrange(factor(redlist_cat, levels=c("Not Evaluated", "Data Deficient", 
                                       "Least Concern", "Near Threatened", 
                                       "Vulnerable", "Endangered",
                                       "Critically Endangered", "Extinct"))) %>%
  mutate(redlist_cat = factor(redlist_cat, levels=c("Not Evaluated", "Data Deficient", 
                                                    "Least Concern", "Near Threatened", 
                                                    "Vulnerable", "Endangered",
                                                    "Critically Endangered", "Extinct")))

soi <- bagged_unknowns_all %>%
  filter(soi == "y")
```

```{r}
print("Number of unknowns predicted in total: ")
nrow(bagged_unknowns_all)
```


```{r}
print("Number of unknowns predicted for each category: ")

bagged_unknowns_all %>%
  group_by(redlist_cat) %>% summarise(n=n())
```

```{r}
print("removing 'Not Evaluated' and 'Least Concern' species")

bagged_unknowns <- bagged_unknowns_all %>%
  filter(redlist_cat != "Least Concern") %>%
  filter(redlist_cat != "Not Evaluated")
```

```{r}
## ADD TREES ----

## get timetree data
chordate_tree <- read.tree("../B_exploreData/timeTree/chordates_species.nwk")

## edit tip labels
chordate_tree$tip.label <- gsub("_", " ", chordate_tree$tip.label)

## get pheno data
phenodata <- read.csv(paste0("../B_exploreData/dataFiles/05.00_pheno_allhomo.csv"))

## create a new DD sample based on whats in the tree
set.seed(1)
data_deficient_sample <- bagged_unknowns %>%
  filter(., organism_name %in% chordate_tree$tip.label) %>%
  filter(., model_type == "Group-specific") %>%
  filter(., redlist_cat == "Data Deficient") %>%
  select(bagged_detrans_predicted_age_mat, name_lab,
         organism_name, common_name, model_group) %>%
  group_by(model_group) %>%
  slice_sample(n = 3, replace = FALSE) %>%
  ungroup()

## create a new EX sample based on whats in the tree
extinct_sample <- bagged_unknowns %>%
  filter(., organism_name %in% chordate_tree$tip.label) %>%
  filter(., model_type == "Group-specific") %>%
  filter(grepl("Extinct", redlist_cat)) %>%
  # filter(., redlist_cat == "Data Deficient") %>%
  select(bagged_detrans_predicted_age_mat, name_lab,
         organism_name, common_name, model_group) %>%
  group_by(model_group) %>%
  # slice_sample(n = 3, replace = FALSE) %>%
  ungroup()

## create a new SOI sample based on whats in the tree
soi_sample <- bagged_unknowns %>%
  filter(., organism_name %in% chordate_tree$tip.label) %>%
  filter(., model_type == "Group-specific") %>%
  filter(., soi == "y") %>%
  select(bagged_detrans_predicted_age_mat, name_lab,
         organism_name, common_name, model_group) %>%
  group_by(model_group) %>%
  # slice_sample(n = 3, replace = FALSE) %>%
  ungroup()
```

```{r}
## CREATE DFS ---- 

## 1. unknowns for group-specific models
unknown_preds <- bagged_unknowns_all %>%
  filter(model != "allhomounknowns") %>%
  select(organism_name, bagged_detrans_predicted_age_mat, common_name) %>%
  mutate(type = "Predicted") %>%
  rename(age_mat = bagged_detrans_predicted_age_mat)

## 2. reported values
reported_age_mat <- read.csv("../../00_dataPrep/figuresTables/Table S[db_age_mat].csv") %>%
  select(age_mat, organism_name, common_name) %>%
  arrange(., organism_name) %>%
  mutate(type = "Reported")

## join
plot_data <- full_join(unknown_preds, reported_age_mat) %>%
  relocate(organism_name, common_name, age_mat) %>%
  mutate(common_name = case_when(
    common_name == "Mueller's borneo gibbon" ~ "Bornean gibbon",
    organism_name == "Sebastes taczanowskii" ~ "White-edged rockfish",
    organism_name == "Pholidichthys leucotaenia" ~ "Engineer goby",
    organism_name == "Neolamprologus leleupi" ~ "Lemon cichlid",
    organism_name == "Lophura swinhoii" ~ "Swinhoe's pheasant",
    organism_name == "Tarsius wallacei" ~ "Wallace's tarsier",
    organism_name == "Copsychus sechellarum" ~ "Seychelles magpie-robin",
    # organism_name == "Scientific name" ~ "Common name",
    TRUE ~ common_name)) %>%
  unique(.)
```

```{r}
## define colours
fish_clr <- viridis_pal(option="D", direction=-1)(4)[2]
maml_clr <- viridis_pal(option="D", direction=-1)(4)[3]
rptl_clr <- viridis_pal(option="D", direction=-1)(4)[4]

## create a new sample based on whats in the tree
set.seed(1)
iucn_sample_unmod <- bagged_unknowns_all %>%
  filter(., organism_name %in% chordate_tree$tip.label) %>%
  filter(., model_type == "Group-specific") %>%
  select(bagged_detrans_predicted_age_mat, name_lab,
         organism_name, common_name, model_group, redlist_cat) %>%
  group_by(model_group, redlist_cat) %>%
  slice_sample(n = 1, replace = FALSE) %>%
  ungroup() %>%
  ## fix names
  mutate(common_name = gsub("american", "American", common_name) %>%
           gsub("african", "African", .))

# levels(factor(iucn_sample_unmod$redlist_cat))

## order df by redlist category
iucn_sample <- iucn_sample_unmod %>%
  arrange(factor(redlist_cat, levels=c("Not Evaluated", "Data Deficient", 
                                      "Least Concern", "Near Threatened", 
                                      "Vulnerable", "Endangered",
                                      "Critically Endangered", "Extinct"))) %>%
  mutate(redlist_cat = factor(redlist_cat, levels=c("Not Evaluated", "Data Deficient", 
                                      "Least Concern", "Near Threatened", 
                                      "Vulnerable", "Endangered",
                                      "Critically Endangered", "Extinct")))
```

```{r}
## import python prediction intervals ----

wd <- "../life_pi-main@764c9a4bf87/outputs/"

## ~SD
naive <- full_join(
  ## fish
  read.csv(paste0(wd, "fishdanio/pred/mapie_naive_medianpred_alpha0.1.csv")), 
  ## mammals
  read.csv(paste0(wd, "mammalshomo/pred/mapie_naive_medianpred_alpha0.1.csv"))) %>%
  ## birds and reptiles
  full_join(read.csv(paste0(wd, "reptilesgallus/pred/mapie_naive_medianpred_alpha0.1.csv"))) %>%
  mutate(method="naive")

## ~boostrapping
jackknife <- full_join(
  ## fish
  read.csv(paste0(wd, "fishdanio/pred/mapie_jackknife_plus_ab_medianpred_alpha0.1.csv")), 
  ## mammals
  read.csv(paste0(wd, "mammalshomo/pred/mapie_jackknife_plus_ab_medianpred_alpha0.1.csv"))) %>%
  ## birds and reptiles
  full_join(read.csv(paste0(wd, "reptilesgallus/pred/mapie_jackknife_plus_ab_medianpred_alpha0.1.csv"))) %>%
  mutate(method="jackknife")

## cv
cv_py <- full_join(
  ## fish
  read.csv(paste0(wd, "fishdanio/pred/mapie_cv_medianpred_alpha0.1.csv")), 
  ## mammals
  read.csv(paste0(wd, "mammalshomo/pred/mapie_cv_medianpred_alpha0.1.csv"))) %>%
  ## birds and reptiles
  full_join(read.csv(paste0(wd, "reptilesgallus/pred/mapie_cv_medianpred_alpha0.1.csv"))) %>%
  mutate(method="cv_py")

## join and edit
python_data <- full_join(naive, jackknife) %>%
  full_join(., cv_py) %>%
              select(-log_predicted_age_mat, 
                     -pred,
                     -detrans_predicted_age_mat) %>%
  rename(age_mat = bagged_detrans_predicted_age_mat) %>%
  rename_with(., ~gsub("pred_", "", .x)) %>%
  mutate(type="Predicted")
```

```{r}
## join data sets
plot_data_all <- plot_data %>%
  select(-common_name) %>%
  mutate(method=ifelse(type=="Predicted", "cv_r", NA_character_)) %>%
  full_join(python_data) %>%
  left_join(., plot_data %>% 
              select(organism_name, common_name) %>%
              unique(.)) %>%
  arrange(organism_name, common_name)
```

```{r fig.width=12.375, fig.height=13.375, message=FALSE}
## CREATE PLOTS (IUCN) ----

mthd <- "jackknife"

## filter data
plot_data_temp <- filter(plot_data_all,
                         method==mthd | is.na(method))
## make plot list
plot_list_temp <- list()

for (rdlst_ct in levels(factor(iucn_sample$redlist_cat))) {
  
  num_rows <- nrow(iucn_sample %>% filter(redlist_cat == rdlst_ct))
  
  for (spp_num in 1:num_rows) {
    
    ## species of interest
    species_of_interest <- (iucn_sample %>%
                              filter(redlist_cat == rdlst_ct) %>%
                              pull(organism_name))[spp_num]
    
    ## model group
    mdl_grp <- (iucn_sample %>%
                  filter(organism_name == species_of_interest) %>%
                  pull(model_group))
    
    ## define colour
    clr <- ifelse(mdl_grp == "Fish", 
                  fish_clr, 
                  ifelse(mdl_grp == "Mammals", 
                         maml_clr, 
                         ifelse(mdl_grp == "Reptiles", 
                                rptl_clr)))
    
    ## subset tree for genome and lifespan species + unknown species of interest
    keep_tips <- intersect(chordate_tree$tip.label, phenodata$organism_name)
    keep_tips <- c(keep_tips, species_of_interest)
    my_tree <- keep.tip(chordate_tree, keep_tips)
    
    ## calculate pairwise distances
    dist_matrix <- cophenetic(my_tree)
    
    ## get the distances for the species of interest
    species_distances <- dist_matrix[species_of_interest,]
    
    ## sort and get the four closest species
    ## (start from 2 because the first one is the distance to itself, which is 0)
    closest_species <- sort(species_distances)[2:5] 
    
    ## extract the names of these species
    closest_species_names <- names(closest_species)
    
    ## get a tree with just those species
    temp_tree <- keep.tip(my_tree, c(closest_species_names, species_of_interest))
    
    ## add data
    temp_data <- data.frame(organism_name=temp_tree$tip.label) %>%
      left_join(., plot_data_temp) %>% 
      relocate(common_name) %>%
      mutate(dummy_redlist_cat = rdlst_ct)
    
    ## edit tip labels again (use common names)
    temp_tree <- treeio::rename_taxa(temp_tree, temp_data, organism_name, common_name)
    
    ## plot it (with divergence time)
    temp_ggtree <- ggtree(temp_tree)+
      theme_tree2()+
      geom_tiplab(as_ylab = TRUE)
    
    temp_ggtree <- revts(temp_ggtree)+
      scale_x_continuous(labels=function(x) scales::comma(abs(x)))
    
    ## make facet plot including age at maturity pointrange plot panel
    temp_ffplot<-facet_plot(temp_ggtree, 
                            panel = "Age at maturity",
                            data=temp_data %>%
                              mutate(upper=ifelse(is.na(upper), age_mat, upper),
                                     lower=ifelse(is.na(lower), age_mat, lower)),
                            geom=geom_pointrangeh,
                            aes(x=age_mat,
                                xmin=upper,
                                xmax=lower,
                                shape=type,
                                size=type),
                            colour=clr,
                            fill=clr)+
      scale_shape_manual(values = c(19, 4))+
      scale_size_manual(values = c(0.7, 0.4))+
      xlim_expand(xlim = c(0, max(temp_data$age_mat)),
                  panel = "Age at maturity") +
      theme(legend.title=element_blank(),
            legend.position = "top",
            strip.background = element_blank(),
            strip.text.x = element_blank(),
            panel.border = element_rect(colour = NA, fill = NA))+
      guides(shape = guide_legend(override.aes = list(linetype = c(1, 0),
                                                      colour = c("black", "black"))))+
      labs(y=temp_data$dummy_redlist_cat)
    
    ## add it to list
    plot_list_temp[[length(plot_list_temp) + 1]] <- temp_ffplot
    
  }
}

## remove y axis title
modified_plot_list_temp <- list()
for (i in 1:length(plot_list_temp)) {
  if (i %in% c(1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19, 20, 22, 23)) {
    ## modify the y-axis label for the selected plots
    plot_list_temp[[i]] <- plot_list_temp[[i]] +
      theme(axis.title.y = element_blank())
  }
  modified_plot_list_temp[[i]] <- plot_list_temp[[i]]
}

## add title (1, 2, 3)
modified_plot_list_temp[[1]] <- modified_plot_list_temp[[1]]+
  ggtitle("Fish")+theme(plot.title = element_text(hjust = 0.5))
modified_plot_list_temp[[2]] <- modified_plot_list_temp[[2]]+
  ggtitle("Mammals")+theme(plot.title = element_text(hjust = 0.5))
modified_plot_list_temp[[3]] <- modified_plot_list_temp[[3]]+
  ggtitle("Reptiles")+theme(plot.title = element_text(hjust = 0.5))

## check
p1_temp <- ggarrange(plotlist = modified_plot_list_temp, 
                     ncol=3, nrow=length(modified_plot_list_temp)/3,
                     common.legend = TRUE)

## label x-axis
ann1 <- ggplot() +
  geom_text(aes(x=0, y=0, label = "Time (MYA)"), size = 3) +
  theme_void()+theme(plot.margin = margin(0,0,0,0))

ann2 <- ggplot() +
  geom_text(aes(x=0, y=0, label = "Age at maturity (years)"), size = 3) +
  theme_void()+theme(plot.margin = margin(0,0,0,0))

ann3 <- ggplot() +
  geom_text(aes(x=0, y=0, label = " "), size = 3) +
  theme_void()+theme(plot.margin = margin(0,0,0,0))

p2_temp <- ggarrange(ann1, ann2, ann3, 
                     ann1, ann2, ann3,
                     ann1, ann2, ann3,
                     nrow=1)

plot_temp <- ggarrange(p1_temp, 
                       p2_temp,
                       heights = c(0.9, 0.025), nrow=2)

## print it
print(mthd)
print(plot_temp)

## save it
ggsave(paste0("figuresTables/Figure [unknowns_", mthd, "].pdf"),
       plot_temp,
       width=8.25*1.5, 
       height=10.25*1.5)

ggsave(paste0("figuresTables/Figure [unknowns_", mthd, "].png"),
       plot_temp,
       width=8.25*1.5, 
       height=10.25*1.5)

ggsave(paste0("figuresTables/Figure [unknowns_", mthd, "].svg"),
       plot_temp,
       width=8.25*1.5, 
       height=10.25*1.5)
```

```{r}
## create supp table
supp_unknowns_preds <- plot_data_all %>%
  filter(method == mthd) %>%
  full_join(., bagged_unknowns_all) %>% 
              # select(-upper, -lower)) #%>%
  select(-method, -type, -model) %>%
  mutate(predicted_age_mat_yrs = round(age_mat, digits=4), 
         predicted_lower_bound_yrs = round(lower, digits=4), 
         predicted_upper_bound_yrs = round(upper, digits=4)) %>%
  rename(scientific_name = organism_name,
         model = model_labs) %>%
  select(scientific_name, common_name,
         predicted_age_mat_yrs, predicted_lower_bound_yrs, predicted_upper_bound_yrs,
         assembly_accession, model,
         redlist_cat, class, order, family, genus) %>%
  arrange(#desc(redlist_cat), 
          scientific_name)

write.csv(supp_unknowns_preds, "figuresTables/Table S[unknowns_preds].csv", row.names=FALSE)
```

```{r fig.width=8, fig.height=4, message=FALSE}
bagged_unknowns_all_less <- bagged_unknowns_all %>% 
  filter(!redlist_cat %in% c("Not Evaluated", 
                             "Data Deficient",
                             "Extinct"))

aov_results <- aov(bagged_detrans_predicted_age_mat ~ redlist_cat, 
                   data=bagged_unknowns_all_less)
tukey_results <- summary(glht(aov_results, linfct=mcp(redlist_cat="Tukey")),
                         test=adjusted("BH"))

temp_cld <- as.data.frame(cld(tukey_results)$mcletters$Letters, rownames=NULL) %>%
  rownames_to_column(var="redlist_cat") %>%
  rename_with(~ ifelse(grepl("Letters", .x), "letters", .x))

redlist_cat_nums <- cbind.data.frame(redlist_cat = c("Least Concern", 
                                          "Near Threatened", 
                                          "Vulnerable", 
                                          "Endangered", 
                                          "Critically Endangered"), 
                          redlist_cat_num = c(1,2,3,4,5))

bagged_unknowns_all_less <- left_join(bagged_unknowns_all_less, redlist_cat_nums) %>%
  mutate(redlist_cat = factor(redlist_cat, levels=c("Not Evaluated", "Data Deficient", 
                                      "Least Concern", "Near Threatened", 
                                      "Vulnerable", "Endangered",
                                      "Critically Endangered", "Extinct")))
```

```{r fig.width=8, fig.height=4.5, message=FALSE}
predicted_data <- bagged_unknowns_all_less %>% 
  select(model_group, organism_name, 
         bagged_detrans_predicted_age_mat, 
         redlist_cat, redlist_cat_num) %>%
  droplevels(.)

plot_data1 <- predicted_data %>% 
  group_by(model_group) %>%
  mutate(r = round(cor(bagged_detrans_predicted_age_mat, redlist_cat_num), 3),
         p = signif(
           cor.test(bagged_detrans_predicted_age_mat, redlist_cat_num)$p.value, 
           digits = 2), 
         lbl = sprintf("R~italic('=')~'%.2f'~','~italic('p =')~'%s'", r, format(p, scientific=TRUE)))

lbls <- paste0(unique(plot_data1$redlist_cat), " (", 
              unique(plot_data1$redlist_cat_num), ")")

redlist_comp_corr_f <- ggplot(plot_data1, 
       aes(x=redlist_cat_num, 
           y=bagged_detrans_predicted_age_mat,
           fill=model_group))+
  geom_jitter(width=0.1, pch=21) +
  scale_fill_manual(values=c(fish_clr, maml_clr, rptl_clr), 
                      guide="none", name="Redlist category")+
  geom_smooth(method="lm", col="black") + 
  ylab("Predicted age at maturity")+
  xlab("Redlist category")+
  facet_wrap(.~model_group, ncol=3)+ 
  geom_text(aes(x = 1.5, y = 7, label = lbl),
            hjust = 0, check_overlap = TRUE, size = 3, parse=T) +
  theme_bw()+
  scale_x_continuous(labels=c(lbls))+
  theme(legend.position = "none",
        axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))

redlist_comp_corr_f

# ggsave("figuresTables/Figure [redlist_comp_corr_f].png", redlist_comp_corr_f, width=8, height=4.5, units="in")
# ggsave("figuresTables/Figure [redlist_comp_corr_f].pdf", redlist_comp_corr_f, width=8, height=4.5, units="in")
```

```{r fig.width=8, fig.height=4.5, message=FALSE}
## repeat for knowns

known_data <- phenodata %>%
  left_join(., redlist_cat_nums) %>%
  mutate(redlist_cat = factor(redlist_cat, levels=c("Not Evaluated", "Data Deficient", 
                                                    "Least Concern", "Near Threatened", 
                                                    "Vulnerable", "Endangered",
                                                    "Critically Endangered", "Extinct"))) %>% 
  filter(!redlist_cat %in% c("Not Evaluated", 
                             "Data Deficient",
                             "Extinct")) %>%
  filter(!is.na(redlist_cat)) %>%
  filter(model_group != "Amphibians") %>%
  droplevels(.) %>% 
  select(model_group, organism_name, 
         mean_age_mat, mean_lifespan, lifespan_imputed,
         redlist_cat, redlist_cat_num)

plot_data2 <- known_data %>%
  group_by(model_group) %>%
  mutate(r = round(cor(mean_age_mat, redlist_cat_num), 3),
         p = signif(
           cor.test(mean_age_mat, redlist_cat_num)$p.value,
           digits = 2),
         lbl = sprintf("R~italic('=')~'%.2f'~','~italic('p =')~'%s'", r, format(p, scientific=TRUE)))

lbls <- paste0(unique(plot_data2$redlist_cat), " (",
              unique(plot_data2$redlist_cat_num), ")")

redlist_comp_corr_fr <- ggplot(plot_data2,
       aes(x=redlist_cat_num,
           y=mean_age_mat,
           fill=model_group))+
  geom_jitter(width=0.1, pch=21) +
  scale_fill_manual(values=c(fish_clr, maml_clr, rptl_clr),
                      guide="none", name="Redlist category")+
  geom_smooth(method="lm", col="black") +
  ylab("Known age at maturity (years)")+
  xlab("Redlist category")+
  facet_wrap(.~model_group, ncol=3)+
  geom_text(aes(x = 1.5, y = 20, label = lbl),
            hjust = 0, check_overlap = TRUE, size = 3, parse=T) +
  theme_bw()+
  scale_x_continuous(labels=c(lbls))+
  theme(legend.position = "none",
        axis.text.x=element_text(angle=90, hjust=1, vjust=0.5))

redlist_comp_corr_fr

# ggsave("figuresTables/Figure S[redlist_comp_corr_fr].png", redlist_comp_corr_fr, width=8, height=4.5, units="in")
```

```{r}
## combine data ----

## import pheno data
phenodata_unknowns <- read.csv("../B_exploreData/dataFiles/00.03_pheno_unknowns.csv")

## add lifeapsn to predicted data
predicted_data2 <- left_join(predicted_data, phenodata_unknowns %>% 
                               select(organism_name, mean_lifespan)) %>%
  mutate(type="Predicted") %>%
  rename(age_mat = bagged_detrans_predicted_age_mat)

## edit known data
known_data2 <- known_data %>%
  select(-lifespan_imputed) %>%
  mutate(type="Known") %>%
  rename(age_mat = mean_age_mat)

## join
all_data <- full_join(predicted_data2, known_data2)
```

```{r fig.width=8, fig.height=6, message=FALSE}
## combined plot ----
plot_data3 <- all_data %>%
  group_by(type, model_group) %>%
  mutate(r = round(cor(age_mat, redlist_cat_num), 3),
         p = signif(
           cor.test(age_mat, redlist_cat_num)$p.value,
           digits = 2),
         lbl = sprintf("R~italic('=')~'%.2f'~','~italic('p =')~'%s'", r, format(p, scientific=TRUE))) %>% 
  ungroup(.) %>%
  group_by(type) %>%
  mutate(ymax=max(age_mat))

lbls <- paste0(unique(plot_data3$redlist_cat), " (",
              unique(plot_data3$redlist_cat_num), ")")

redlist_comp_corr_b <- ggplot(plot_data3,
       aes(x=redlist_cat_num,
           y=age_mat,
           fill=model_group))+
  geom_jitter(width=0.1, pch=21) +
  scale_fill_manual(values=c(fish_clr, maml_clr, rptl_clr),
                      guide="none", name="Redlist category")+
  geom_smooth(method="lm", col="black") +
  ylab("Age at maturity (years)")+
  xlab("Redlist category")+
  facet_grid(type~model_group, scales="free")+
  geom_text(aes(x = 1.5, 
                y = ymax,
                label = lbl),
            hjust = 0, check_overlap = TRUE, size = 3, parse=T) +
  theme_bw()+
  scale_x_continuous(labels=c(lbls))+
  theme(legend.position = "none",
        axis.text.x=element_text(angle=90, hjust=1, vjust=0.5),
        strip.text=element_text(size=10),
        strip.background = element_blank())

redlist_comp_corr_b

ggsave("figuresTables/Figure [redlist_comp_corr_b].png", redlist_comp_corr_b, width=8, height=6, units="in")
ggsave("figuresTables/Figure [redlist_comp_corr_b].pdf", redlist_comp_corr_b, width=8, height=6, units="in")
ggsave("figuresTables/Figure [redlist_comp_corr_b].svg", redlist_comp_corr_b, width=8, height=6, units="in")
```

```{r}
## impute or add lifespan where missing ----
missing_lifespans <- sort(all_data %>% filter(is.na(mean_lifespan)) %>% pull(organism_name))
paste("species with no lifespan info:")
missing_lifespans

tax_rank_info <- rbind(phenodata %>% select(organism_name, class, order, family, genus), 
                       phenodata_unknowns %>% select(organism_name, class, order, family, genus))

## subset the data for species specific information
impute_lifespan <- all_data %>%
  ## add order etc info back in
  left_join(., tax_rank_info) %>%
  select(organism_name, class, order, family, genus, mean_lifespan) %>%
  group_by(genus) %>%
  add_tally() %>%
  mutate(lifespan_imputed1 = ifelse(is.na(mean_lifespan),
                                    mean(mean_lifespan, na.rm=TRUE),
                                    mean_lifespan)) %>%
  ungroup(.) %>%
  select(-n) %>%
  group_by(family) %>%
  add_tally() %>%
  mutate(lifespan_imputed2 = ifelse(is.na(lifespan_imputed1),
                                    mean(mean_lifespan, na.rm=TRUE),
                                    lifespan_imputed1)) %>%
  ungroup(.) %>%
  select(-n) %>%
  group_by(order) %>%
  add_tally() %>%
  mutate(lifespan_imputed3 = ifelse(is.na(lifespan_imputed2),
                                    mean(mean_lifespan, na.rm=TRUE),
                                    lifespan_imputed2)) %>%
  ungroup(.) %>%
  select(-n) %>%
  group_by(class) %>%
  add_tally() %>%
  mutate(lifespan_imputed4 = ifelse(is.na(lifespan_imputed3),
                                    mean(mean_lifespan, na.rm=TRUE),
                                    lifespan_imputed3)) %>%
  ungroup(.) %>%
  select(-n) %>%
  group_by(order) %>%
  add_tally() %>%
  mutate(lifespan_imputed = ifelse(is.na(lifespan_imputed4),
                                   mean(mean_lifespan, na.rm=TRUE),
                                   lifespan_imputed4)) %>%
  ungroup(.) %>%
  select(organism_name, lifespan_imputed)

## missing
missing_imputed_lifespans <- impute_lifespan %>% filter(is.na(lifespan_imputed))

paste("species for which lifespan could not be imputed by kNN (ideally none but may be present for non-actinopterygian fish)")
missing_imputed_lifespans

all_data <- all_data %>%
  left_join(., impute_lifespan) %>%
  filter(!organism_name %in% missing_imputed_lifespans$organism_name)
```


```{r fig.width=8, fig.height=6, message=FALSE}
## combined aml plot NB "unknown" lifespans mostly imputed

## combined plot ----
plot_data4 <- all_data %>%
  mutate(aml_ratio=lifespan_imputed/age_mat) %>%
  group_by(type, model_group) %>%
  mutate(r = round(cor(aml_ratio, redlist_cat_num), 3),
         p = signif(
           cor.test(aml_ratio, redlist_cat_num)$p.value,
           digits = 2),
         lbl = sprintf("R~italic('=')~'%.2f'~','~italic('p =')~'%s'", r, format(p, scientific=TRUE))) %>% 
  ungroup(.) %>%
  group_by(type) %>%
  mutate(ymax=max(aml_ratio))

lbls <- paste0(unique(plot_data4$redlist_cat), " (",
              unique(plot_data4$redlist_cat_num), ")")

redlist_comp_corr_bs <- ggplot(plot_data4,
       aes(x=redlist_cat_num,
           y=aml_ratio,
           fill=model_group))+
  geom_jitter(width=0.1, pch=21) +
  scale_fill_manual(values=c(fish_clr, maml_clr, rptl_clr),
                      guide="none", name="Redlist category")+
  geom_smooth(method="lm", col="black") +
  ylab("Relative age at maturity")+
  xlab("Redlist category")+
  facet_grid(type~model_group, scales="free")+
  geom_text(aes(x = 1.5, 
                y = ymax,
                label = lbl),
            hjust = 0, check_overlap = TRUE, size = 3, parse=T) +
  theme_bw()+
  scale_x_continuous(labels=c(lbls))+
  theme(legend.position = "none",
        axis.text.x=element_text(angle=90, hjust=1, vjust=0.5), 
        strip.text=element_text(size=10),
        strip.background = element_blank())

redlist_comp_corr_bs

ggsave("figuresTables/Figure S[redlist_comp_corr_bs].png", redlist_comp_corr_bs, width=8, height=6, units="in")
ggsave("figuresTables/Figure S[redlist_comp_corr_bs].pdf", redlist_comp_corr_bs, width=8, height=6, units="in")
```
```{r}
## edit all data for supplementary 
supp_data <- all_data %>%
  mutate(lifespan_type=ifelse(is.na(mean_lifespan), "Known", "Imputed")) %>%
  rename(age_mat_type=type,
         lifespan=lifespan_imputed) %>%
  select(model_group, organism_name, redlist_cat, 
         age_mat, age_mat_type, lifespan, lifespan_type) %>%
  arrange(model_group, organism_name)

write.csv(supp_data, "figuresTables/Table S[aml_iucn].csv", row.names=FALSE)
```

```{r}
## count species
nrow(supp_data %>% filter(age_mat_type=="Predicted"))
nrow(supp_data %>% filter(age_mat_type=="Known"))
```


```{r}
## END SCRIPT
```


